# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci

language: haskell

cache:
  directories:
   - $HOME/.cabal/store

cabal: 3.0
ghc:
  - "8.8.1"
  - "8.6.5"
  - "8.4.4"
  - "8.2.2"
  - "8.0.2"
  - "7.10.3"
  - "7.8.4"
  - "7.6.3"
  - "7.4.2"

before_install:
  - sudo apt-get -y install libbrotli-dev

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build
 - cabal check
